import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use | AICostLens",
  description: "Terms for using AICostLens AI spend audit estimates and saved reports."
};

const sections = [
  {
    title: "Use Of The Product",
    body:
      "AICostLens provides an AI spend audit based on the information you enter. You agree to use the product lawfully and to avoid submitting data that you do not have permission to use."
  },
  {
    title: "Estimates, Not Financial Advice",
    body:
      "Audit results are estimates based on current pricing research, rule-based recommendations, and optional AI-generated summary text. They are not financial, legal, procurement, or tax advice. You should verify vendor pricing and contract terms before making purchasing decisions."
  },
  {
    title: "Accuracy Of Inputs",
    body:
      "Savings estimates depend on accurate monthly spend, seat count, team size, and use-case inputs. If those inputs are incomplete or incorrect, the recommendations may be incomplete or incorrect too."
  },
  {
    title: "No Guaranteed Savings",
    body:
      "AICostLens may recommend downgrades, consolidation, alternative vendors, or discounted-credit conversations. We do not guarantee that a vendor will honor a price, that credits will be available, or that every recommendation will fit your team."
  },
  {
    title: "Shareable Reports",
    body:
      "You may share public report URLs generated by the product. Public reports intentionally hide lead details, but they may still reveal stack and spend patterns. You are responsible for deciding whether a report is safe for your audience."
  },
  {
    title: "Contact",
    body:
      "For questions about these terms or a saved report, contact info@aicostlens.shop."
  }
];

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-4xl px-4 py-12 lg:px-8">
      <Link className="text-sm font-medium text-primary hover:underline" href="/">
        Back to audit
      </Link>

      <section className="mt-8">
        <p className="text-sm font-semibold uppercase tracking-wide text-primary">
          Last updated May 25, 2026
        </p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight text-foreground">
          Terms of Use
        </h1>
        <p className="mt-4 text-lg leading-8 text-muted-foreground">
          These terms keep expectations clear: AICostLens helps teams reason about AI spend, but
          final procurement decisions stay with you.
        </p>
      </section>

      <div className="mt-10 grid gap-5">
        {sections.map((section) => (
          <section key={section.title} className="rounded-lg border border-border bg-white p-6">
            <h2 className="text-xl font-semibold text-foreground">{section.title}</h2>
            <p className="mt-3 leading-7 text-muted-foreground">{section.body}</p>
          </section>
        ))}
      </div>
    </main>
  );
}
